name: grosa_store
description: Online Grocery Store.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^1.22.0
  provider: ^6.0.3
  cloud_firestore: ^3.4.7
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.2.1
  firebase_auth: ^3.8.0
  flutter_facebook_auth: ^4.4.1
  google_sign_in: ^5.4.1
  url_strategy: ^0.2.0
  responsive_builder: ^0.4.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/home/
