// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdMHL0qeUw6CUVSipZ-g-ziPBeT6hUaFY',
    appId: '1:1016845620587:web:b8e4ecdac8eb37ee4ea82e',
    messagingSenderId: '1016845620587',
    projectId: 'grosa-store',
    authDomain: 'grosa-store.firebaseapp.com',
    storageBucket: 'grosa-store.appspot.com',
    measurementId: 'G-97VQ8BHDH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQcLtxDsQW0rK9M70CIGrAhlE_-Z9CcU',
    appId: '1:1016845620587:android:ce26078135ca9e204ea82e',
    messagingSenderId: '1016845620587',
    projectId: 'grosa-store',
    storageBucket: 'grosa-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9nHfPZBwc585-eqeJQbwLDNQGpisKvog',
    appId: '1:1016845620587:ios:17cb8eb232bb47e04ea82e',
    messagingSenderId: '1016845620587',
    projectId: 'grosa-store',
    storageBucket: 'grosa-store.appspot.com',
    androidClientId: '1016845620587-ksoek1htkcnsp1kvk9i5aq62do9ljhdp.apps.googleusercontent.com',
    iosClientId: '1016845620587-e8psh0g12tnqs65erjmd6njc3icvpr9h.apps.googleusercontent.com',
    iosBundleId: 'io.cloutdevelopers.grosaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9nHfPZBwc585-eqeJQbwLDNQGpisKvog',
    appId: '1:1016845620587:ios:17cb8eb232bb47e04ea82e',
    messagingSenderId: '1016845620587',
    projectId: 'grosa-store',
    storageBucket: 'grosa-store.appspot.com',
    androidClientId: '1016845620587-ksoek1htkcnsp1kvk9i5aq62do9ljhdp.apps.googleusercontent.com',
    iosClientId: '1016845620587-e8psh0g12tnqs65erjmd6njc3icvpr9h.apps.googleusercontent.com',
    iosBundleId: 'io.cloutdevelopers.grosaStore',
  );
}
